repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2  # Use the latest version
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --unsafe-fixes]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
