apiVersion: v1
kind: Secret
metadata:
  name: redis-memory-server-secrets
  namespace: redis-memory-server
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  # echo -n "your-redis-url" | base64
  REDIS_URL: ""
  # echo -n "your-openai-key" | base64
  OPENAI_API_KEY: ""
  # echo -n "your-anthropic-key" | base64
  ANTHROPIC_API_KEY: ""
---
# Example of how to create the secret with kubectl:
# kubectl create secret generic redis-memory-server-secrets \
#   --namespace=redis-memory-server \
#   --from-literal=REDIS_URL="redis://redis:6379" \
#   --from-literal=OPENAI_API_KEY="your-openai-key" \
#   --from-literal=ANTHROPIC_API_KEY="your-anthropic-key"
